name: Deploy pipeline
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # Add your Docker Hub credentials to your GitHub repository secrets
  # as DOCKER_USERNAME and DOCKER_PASSWORD
  test-server:
    name: testing-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - run: >-
          docker build -t aliwoodman101/fullstack-mern-server -f
          server/Dockerfile.dev ./server
      - run: docker run -e CI=true aliwoodman101/fullstack-mern-server npm test
  test-client:
    name: testing-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - run: >-
          docker build -t aliwoodman101/fullstack-mern-client -f
          client/Dockerfile.dev ./client
      - run: docker run -e CI=true aliwoodman101/fullstack-mern-client npm test
      - run: docker build -t aliwoodman101/mern-client ./client
      - run: docker build -t aliwoodman101/mern-nginx ./nginx
      - run: docker build -t aliwoodman101/mern-server ./server
      - run: docker push aliwoodman101/mern-client
      - run: docker push aliwoodman101/mern-nginx
      - run: docker push aliwoodman101/mern-server
  deploy-to-aws:
    name: deploy-aws
    runs-on: ubuntu-latest
    needs: [test-client, test-server]
    steps:
      - uses: actions/checkout@v3
      - run: zip -r deploy.zip . -x '*.git*'
      - uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: "${{ secrets.AWS_ACCESS_KEY }}"
          aws_secret_key: "${{ secrets.AWS_SECRET_KEY }}"
          application_name: mern-beanstalk
          environment_name: Mern-beanstalk-env
          existing_bucket_name: elasticbeanstalk-eu-west-1-767398134333
          region: eu-west-1
          version_label: "${{ github.sha }}"
          deployment_package: deploy.zip
